export const dataCategory = [
  {
    id_cat: 1,
    name: 'Оренда автомобіля з маніпулятором',
    img: './images/Kamaz/Kamaz.jpeg',
  },
  {
    id_cat: 2,
    name: 'Оренда компресорів пересувних дизельних гвинтових',
    img: './images/PD71/PD71.jpeg',
  },
  {
    id_cat: 3,
    name: 'Оренда компресорів стаціонарних електричних гвинтових',
    img: './images/CompressorElectricSt/CompressorElectricSt.jpeg',
  },
  {
    id_cat: 4,
    name: 'Оренда обладнання для сухого абразивне-струминного очищення (піскоструй)',
    img: './images/Piskostrui.png',
  },
  {
    id_cat: 5,
    name: 'Оренда обладнання для фарбування та нанесення гідроізоляції',
    img: './images/drawingEquipment.png',
  },
  {
    id_cat: 6,
    name: 'Оренда дробе-метного обладнання',
    img: './images/ShotBlastingEquipment/ShotBlastingEquipment.png',
  },
  {
    id_cat: 7,
    name: 'Оренда теплогенератора дизельного',
    img: './images/HeatGenerator/HeatGenerator.JPG',
  },
  {
    id_cat: 8,
    name: 'Оренда обладнання для мокрого абразивне-струминного очищення',
    img: './images/PiskostruiWater/PiskostruiWater.jpg',
  },
  {
    id_cat: 9,
    name: 'Оренда робочих платформ підвісних',
    img: './images/suspendPlatform.png',
  },
  {
    id_cat: 10,
    name: 'Оренда обладнання для сухого торкретування',
    img: './images/shotcrete.png',
  },
  { id_cat: 11, name: 'Оренда вишки тури', img: './images/towers.png' },

  {
    id_cat: 12,
    name: 'Оренда установки збору та очищення абразиву електричної',
    img: './images/abrasiveCleaning.png',
  },
];
export const dataEquipment = [
  {
    id_eq: 1,
    img: '/images/PD71/PD71.jpeg',
    images: [
      '/images/PD71/PD71_1.jpeg',
      '/images/PD71/PD71_2.jpeg',
      '/images/PD71/PD71_3.jpeg',
      '/images/PD71/PD71_4.jpeg',
    ],
    name: 'Дизельний гвинтовий компресор ATMOS PD-71',
    text: 'Продуктивність - 7,6 куб.м/хв. Робочий тиск - 7,0 бар. Максимальний тиск - 8,6 бар.',
    description: '/docxFiles/PD71/PD71_description.docx',
    characteristics: '/docxFiles/PD71/PD71_characteristics.docx',
    instructions: '/docxFiles/PD71/PD71_instructions.docx',
    priceInfo: ['1-2 дня', '3-6 днів', 'Ціна за місяць', 'Застава'],
    price: [2500, 2500, 7500, 30000],
    id_cat: 2,
  },
  {
    id_eq: 2,
    img: '/images/PD130/PD130.jpeg',
    images: [
      '/images/PD130/PD130_1.jpeg',
      '/images/PD130/PD130_2.jpeg',
      '/images/PD130/PD130_3.jpeg',
      '/images/PD130/PD130_4.jpeg',
      '/images/PD130/PD130_5.jpeg',
      '/images/PD130/PD130_6.jpeg',
    ],
    name: 'Дизельний гвинтовий компресор ATMOS PD-130',
    text: 'Продуктивність - 16,7 куб.м/хв. Робочий тиск - 7,0 бар. Максимальний тиск - 8,6 бар.',
    description: '/docxFiles/PD130/PD130_description.docx',
    characteristics: '/docxFiles/PD130/PD130_characteristics.docx',
    instructions: '/docxFiles/PD130/PD130_instructions.docx',
    priceInfo: ['1-2 дня', '3-6 днів', 'Ціна за місяць', 'Застава'],
    price: [5000, 5000, 150000, 60000],
    id_cat: 2,
  },
  {
    id_eq: 3,
    img: '/images/CompressorElectricSt/CompressorElectricSt.jpeg',
    images: [
      '/images/CompressorElectricSt/CompressorElectricSt_1.jpeg',
      '/images/CompressorElectricSt/CompressorElectricSt_2.jpeg',
      '/images/CompressorElectricSt/CompressorElectricSt_3.jpeg',
      '/images/CompressorElectricSt/CompressorElectricSt_4.jpeg',
      '/images/CompressorElectricSt/CompressorElectricSt_5.jpeg',
      '/images/CompressorElectricSt/CompressorElectricSt_6.jpeg',
      '/images/CompressorElectricSt/CompressorElectricSt_7.jpeg',
      '/images/CompressorElectricSt/CompressorElectricSt_8.jpeg',
      '/images/CompressorElectricSt/CompressorElectricSt_9.jpeg',
      '/images/CompressorElectricSt/CompressorElectricSt_10.jpeg',
    ],
    name: 'Стаціонарний електричний гвинтовий  компресор',
    text: 'Продуктивність - 7,6 куб.м/хв. Робочий тиск - 7,0 бар. Максимальний тиск - 8,6 бар.',
    description: '/docxFiles/StCompressor/StCompressor_description.docx',
    characteristics:
      '/docxFiles/StCompressor/StCompressor_characteristics.docx',
    instructions: '/docxFiles/StCompressor/StCompressor_instructions.docx',
    priceInfo: ['1-2 дня', '3-6 днів', 'Ціна за місяць', 'Застава'],
    price: [5000, 5000, 150000, 60000],
    id_cat: 3,
  },
  {
    id_eq: 4,
    img: '/images/ShotBlastingEquipment/ShotBlastingEquipment_1.jpg',
    images: [
      '/images/ShotBlastingEquipment/ShotBlastingEquipment_1.jpg',
      '/images/ShotBlastingEquipment/ShotBlastingEquipment_2.jpg',
      '/images/ShotBlastingEquipment/ShotBlastingEquipment_3.jpg',
    ],
    name: 'Дробе-метне обладнання',
    text: 'Продуктивність - 50 м2/год. метал/100 м2/год. бетон Ширина очищення  – 520 мм  Електродвигун – 400Вт/50Гц/20 кВт',
    description:
      '/docxFiles/shotBlastingEquipment/shotBlastingEquipment_description.docx',
    characteristics:
      '/docxFiles/shotBlastingEquipment/shotBlastingEquipment_characteristics.docx',
    instructions:
      '/docxFiles/shotBlastingEquipment/shotBlastingEquipment_instructions.docx',
    priceInfo: ['1-2 дня', '3-6 днів', 'Ціна за місяць', 'Застава'],
    price: ['Договірна', 'Договірна', 'Договірна', 'Договірна'],
    id_cat: 6,
  },
  {
    id_eq: 5,
    img: '/images/Kamaz/Kamaz.jpeg',
    images: [
      '/images/Kamaz/Kamaz_1.jpeg',
      '/images/Kamaz/Kamaz_2.jpeg',
      '/images/Kamaz/Kamaz_3.jpeg',
    ],
    name: 'Автомобіль з маніпулятором',
    text: 'Перевезення вантажу – до 10 тон. Вантажопідйомність маніпулятора – до 5 тон. Розмір платформи Д/Ш, м – 6,2/2,4. Працюємо по всій Україні. Водій наш.',
    description: '/docxFiles/.docx',
    characteristics: '/docxFiles/.docx',
    instructions: '/docxFiles/.docx',
    priceInfo: ['4 год.', '8 год.', 'грн./км', 'Застава'],
    price: [5000, 9600, 52, 0],
    id_cat: 1,
  },
];
